# Generated by Django 3.2 on 2023-05-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Planejamento', 'Planejamento'), ('Execução', 'Execução'), ('Monitoramento', 'Monitoramento'), ('Concluído', 'Concluído')], default='Planejamento', max_length=20, verbose_name='Status'),
        ),
    ]
